### ISSUE TITLE
Documentation "BeckhoffDoku_EN.pptx" can not be opened.

### ISSUE THREAD

**Issue by X-Berger** [2onk/UniversalRobots-Beckhoff#1]
Trying to open the documentation file "BeckhoffDoku_EN.pptx" an error occurs. 
Error-message: "PowerPoint found a problem with contend in E:\EXT\QC\BeckhoffDoku_EN.pptx"

Please reupload the file.

**Comment by 2onk** [comment]
Thank you for reporting the issue. 
It still worked out for several more users.

I have exchanged the power point to a .pdf which should be easily readable.

**Comment by X-Berger** [comment]
Great, thx for the quick fixing and your reply.
